# Change these first
owner: compusport # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: CompuSport Landing
    url: https://compusport.us
  - name: CompuSport Player App
    url: https://compusport.us/app
  - name: CompuSport Manager App
    url: https://compusport.us/cs
 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CompuSport Status
  introTitle: "**Current Status** of all CompuSport apps"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
